### PR TITLE
Added database design

### PR DESCRIPTION
**Pull request by scottmhogan**
Review Database Design.png before pushing to master

### CODE REVIEW

**Comment by Sarefx** [comment]
I think need to add Hours for the clinic if we going to go by Clinic class diagram. Otherwise looks good

**Comment by jsjong** [comment]
Maybe connect patient and clinic by location or nearest location so patient has a way to find a clinic

**Comment by malimban** [comment]
@jsjong Maybe something like Current Clinic?
I'd imagine that a doctor can have many patients, is the assignedPatients in doctor a table?
Looks good though! There are no views nor controllers, which is great.

**Comment by scottmhogan** [comment]
assignedPatients under doctor is just varchar now, once I have access to the database in class I will look into seeing if it is possible to turn it into a table. I also transcribed the picture into editable text if anyone wants to manipulate it before merging to master

**Pull request merged**
